### ISSUE TITLE
AttributeError: 'UNetSpatioTemporalConditionModel' object has no attribute 'module'. Did you mean: 'modules'?

### ISSUE THREAD

**Issue by dailingx** [pixeli99/SVD_Xtend#12]
I got an error when I run with: accelerate launch train_svd.py     --pretrained_model_name_or_path=/root/stable-video-diffusion-img2vid-xt     --output_dir="model_out"     --per_gpu_batch_size=1 --gradient_accumulation_steps=1     --max_train_steps=50000     --width=512     --height=320     --checkpointing_steps=1000 --checkpoints_total_limit=1     --learning_rate=1e-5 --lr_warmup_steps=0     --seed=123     --mixed_precision="fp16"     --validation_steps=200

train_dataloader is <accelerate.data_loader.DataLoaderShard object at 0x7f4c101b5150>
Traceback (most recent call last):
  File "/root/SVD_Xtend/train_svd.py", line 1246, in <module>
    main()
  File "/root/SVD_Xtend/train_svd.py", line 1025, in main
    added_time_ids = _get_add_time_ids(
  File "/root/SVD_Xtend/train_svd.py", line 940, in _get_add_time_ids
    passed_add_embed_dim = unet.module.config.addition_time_embed_dim * \
  File "/root/SVD_Xtend/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 222, in __getattr__
    return super().__getattr__(name)
  File "/root/SVD_Xtend/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UNetSpatioTemporalConditionModel' object has no attribute 'module'. Did you mean: 'modules'?

**Comment by pixeli99** [comment]
hi,

Same as #2

**Comment by dailingx** [comment]
Thanks, this is very useful.
