### ISSUE TITLE
Error when I start the training

### ISSUE THREAD

**Issue by andreichisilev** [pixeli99/SVD_Xtend#46]
I get an error about the UNetSpatioTemporalConditionModel. 
This is the Traceback:
Traceback (most recent call last):
  File "/workspace/SVD_Xtend/train_svd.py", line 1255, in <module>
    main()
  File "/workspace/SVD_Xtend/train_svd.py", line 1043, in main
    added_time_ids = _get_add_time_ids(
  File "/workspace/SVD_Xtend/train_svd.py", line 951, in _get_add_time_ids
    expected_add_embed_dim = unet.module.add_embedding.linear_1.in_features
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 218, in __getattr__
    return super().__getattr__(name)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UNetSpatioTemporalConditionModel' object has no attribute 'module'

**Comment by jhj7905** [comment]
@andreichisilev 
You can solve it with https://github.com/pixeli99/SVD_Xtend/issues/2
